config/routes.rb
Streamphish::Application.routes.draw do
  devise_for :users
  namespace :api do
    namespace :v1 do
      resources :shows
      resources :songs
    end
  end

  get '/shows/:id/:song', to: 'shows#show', constraints: { id: /\d{4}-\d{1,2}-\d{1,2}/ }

  resources :shows, only: [:show]
  resources :songs, only: [:index, :show]

  resources :sitemaps, only: [:index, :show] do
    collection do
      get :sections
      get :songs
      get 'shows/:date', to: :show_by_date,  constraints: { date: /\d{4}-\d{1,2}-\d{1,2}/ }, as: :show_by_date
      get 'shows/:year', to: :shows_by_year, constraints: { year: /\d{4}|83\-87/ },          as: :shows_by_year
    end
  end

  root :to => 'pages#index'

end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
  def index
  end

  def sections
  end

  def songs
    @songs = Song.where('tracks_count > 0').order(:title)
  end

  def shows_by_year
    @shows = Show.for_year params[:year]
  end

  def show_by_date(date)
  end
end

app/views/sitemaps/index.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc><%= sections_sitemaps_url(format: :xml) %></loc>
    <lastmod><%= Time.now.strftime("%Y-%m-%dT%H:%M:%SZ") %></lastmod>
  </sitemap>              
  <sitemap>
    <loc><%= songs_sitemaps_url(format: :xml) %></loc>
    <lastmod><%= Time.now.strftime("%Y-%m-%dT%H:%M:%SZ") %></lastmod>
  </sitemap>
  <%- @years.each do |year| %>
  <sitemap>
    <loc><%= shows_by_year_sitemaps_url(year: year[:year], format: :xml) %></loc>
    <lastmod><%= Time.now.strftime("%Y-%m-%dT%H:%M:%SZ") %></lastmod>
  </sitemap>
  <% end %>
</sitemapindex>

app/views/sitemaps/sections.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
  <url> 
    <loc><%= root_url %></loc> 
    <lastmod><%= Time.now.strftime("%Y-%m-%dT%H:%M:%SZ") %></lastmod>
    <changefreq>daily</changefreq>
  </url>
  <url> 
    <loc><%= songs_url %></loc> 
    <lastmod><%= Time.now.strftime("%Y-%m-%dT%H:%M:%SZ") %></lastmod>
    <changefreq>daily</changefreq>
  </url>
  <%- @years.each do |year| %>
  <url> 
    <loc><%= show_url(year[:year]) %></loc> 
    <lastmod><%= Time.now.strftime("%Y-%m-%dT%H:%M:%SZ") %></lastmod>
    <changefreq>daily</changefreq>
  </url>
  <% end %>
</urlset>

app/views/sitemaps/shows_by_year.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
  <%- @shows.each do |show| %>
  <url> 
    <loc><%= show_url(show) %></loc> 
    <lastmod><%= show.updated_at.strftime("%Y-%m-%dT%H:%M:%SZ") %></lastmod>
    <changefreq>weekly</changefreq>
  </url>
  <%- end %>
</urlset>

app/views/sitemaps/songs.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
  <%- @songs.each do |song| %>
  <url> 
    <loc><%= song_url(song) %></loc> 
    <lastmod><%= song.updated_at.strftime("%Y-%m-%dT%H:%M:%SZ") %></lastmod>
    <changefreq>daily</changefreq>
  </url>
  <%- end %>
</urlset>