config/routes.rb
Streamphish::Application.routes.draw do
  devise_for :users
  namespace :api do
    namespace :v1 do
      resources :shows
      resources :songs
    end
  end

  get '/shows/:id/:song', to: 'shows#show', constraints: { id: /\d{4}-\d{1,2}-\d{1,2}/ }

  resources :shows, only: [:show]
  resources :songs, only: [:index, :show]

  resources :sitemaps, only: [:index, :show] do
    collection do
      get :sections
      get :songs
      get 'shows/:date', to: :show_by_date,  constraints: { date: /\d{4}-\d{1,2}-\d{1,2}/ }, as: :show_by_date
      get 'shows/:year', to: :shows_by_year, constraints: { year: /\d{4}|83\-87/ },          as: :shows_by_year
    end
  end

  root :to => 'pages#index'

end

app/views/pages/_song_bubble.html.erb
<% bg, fg = random_bg_and_text_colors %>

<a href="<%= song_path(song) %>" style="background: <%= bg %>; color: <%= fg %>" <%= lighter_hover_inline_js(bg) %>>
  <span><%= song.title %></span>
</a>

app/views/pages/_year_bubble.html.erb
<% bg, fg = random_bg_and_text_colors %>

<li class="<%= translucent_if_empty(year) %>" style="background: <%= bg %>; border: 1px solid <%= bg %>;" <%= lighter_hover_inline_js(bg) %>>
  <%= link_to "<span>#{year}</span>".html_safe, shows_path(:year => year), :style => "color: #{fg};" %>
</li>

app/views/pages/index.html.erb
<% content_for :pt_data do %>
  <%= render(:template => 'pages/index', :formats => [:json]).html_safe %>
<% end %>

<% content_for(:title) { "PhishTracks" } %>

<div id="currentView">
  <header>
    <h1>PhishTracks</h1>
  </header>

  <ul class="pageList linkItems">
    <li class="sectionTitle"><h2>Years</h2></li>
    <% @years.reverse.each do |year| %>
    <li>
      <a href="/shows/<%= year[:year] %>"><span><%= year[:year] %></span></a>
    </li>
    <% end %>

    <li class="sectionTitle"><h2>Songs</h2></li>
    <% @songs.each do |song| %>
    <li>
      <a href="/songs/<%= song.slug %>"><span><%= song.title %></span></a>
    </li>
    <% end %>
  </ul>
</div>

app/views/pages/years.html.erb
<% content_for(:title) { "Years :: StreamPhish" } %>

<h1 class="pageListHeader">
  Years
  <%= back_link_for @years %>
</h1>
<ul class="pageList linkItems showsByYear">
<% @years.each do |year| %>
  <% year_html = year_empty?(year) ? "<span>#{year}</span>" : "<span><strong>#{year}</strong></span>" %>
  <li><%= link_to year_html.html_safe, shows_path(:year => year) %></li>
<% end %>
</ul>